import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Providers from '@/components/Providers'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className= {`${inter.className} w-10/12 mx-auto`}>
      <Providers>
          <Header />
          <main className="px-8 md:px-28">{children}</main>
          <Footer/>
        </Providers>
          </body>
    </html>
  )
}
